---
services:
  httpd:
    container_name: httpd
    image: httpd:2.4
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.httpd.entrypoints=http"
      - "traefik.http.routers.httpd.rule=Host(`httpd.${ROOT_DOMAIN}`)"
      - "traefik.http.middlewares.httpd-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.httpd.middlewares=httpd-https-redirect"
      - "traefik.http.routers.httpd-secure.entrypoints=https"
      - "traefik.http.routers.httpd-secure.rule=Host(`httpd.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.httpd-secure.tls=true"
      - "traefik.http.routers.httpd-secure.service=httpd"
      - "traefik.http.services.httpd.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
