services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${CONTAINER_USER_ID}:${CONTAINER_GROUP_ID}
    restart: 'unless-stopped'
    group_add:
      - "${RENDER_HOST_GUID}" # "render" host group id (getent group render | cut -d: -f3)
#    network_mode: 'host' # only needed for DLNA
    ports:
      - 8016:8096
    volumes:
      - "${CONFIGS}/jellyfin-config:/config"
      - "/tmp/jellyfin-cache:/cache"
      - "${MEDIA}/movies:/movies"
      - "${MEDIA}/music:/music"
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
      - "/dev/dri/renderD129:/dev/dri/renderD129"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${ROOT_DOMAIN}`)"
      - "traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-https-redirect"
      - "traefik.http.routers.jellyfin-secure.entrypoints=https"
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    # Optional - alternative address used for autodiscovery
    environment:
      - "JELLYFIN_PublishedServerUrl=http://jellyfin.${ROOT_DOMAIN}"

    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
