---
services:

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    volumes:
      - nextcloud_data:/var/www/html
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - proxy
    depends_on:
      - mydb
      - redis
    environment:
      - TZ=Europe/Oslo
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS="nc.${ROOT_DOMAIN}"
      - NC_maintenance_window_start=1
      - NC_default_phone_region=no
      - NC_default_language=en
      - NC_default_locale=nb_NO
      - TRUSTED_PROXIES=192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
      - APACHE_DISABLE_REWRITE_IP=1
      - MYSQL_HOST=mydb
      - MYSQL_DATABASE=nc
      - MYSQL_USER=user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`nc.${ROOT_DOMAIN}`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nc-header.headers.customResponseHeaders.Strict-Transport-Security=15552000"
      - "traefik.http.middlewares.nc-rep.redirectregex.regex='https://(.*)/.well-known/(?:card|cal)dav'"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement='https://$${1}/remote.php/dav'"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.routers.nextcloud.middlewares=nc-header,nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nc.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.routers.nextcloud-secure.middlewares=nc-rep,nc-header"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.services.nextcloud.loadbalancer.passHostHeader=true"
      - "traefik.docker.network=proxy"

  mydb:
    image: mariadb:11.3.2
    container_name: mydb
    hostname: mydb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - proxy
    environment:
      - TZ=Europe/Oslo
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # replace with a stronger password
      - MYSQL_DATABASE=nc
      - MYSQL_USER=user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} # set a stronger password in a .env file

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - proxy

# Consider using directories instead of volumes for easier backups
volumes:
  db-data:
  nextcloud_data:

networks:
  nc: