---
version: "3.7"
services:
  ts-authkey-test:
    image: tailscale/tailscale:latest
    container_name: ts-authkey-test
    hostname: authkey-test
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/talscale
    volumes:
      - ${PWD}/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  nextcloud:
    image: nextcloud:latest
    volumes:
      - ./nextcloud_data:/var/www/html
    environment: []
    network_mode: "service:ts-authkey-test"
    restart: unless-stopped